// This file was autogenerated by /home/ren/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../src/board.js', ['drecco.sudokill.Board'], ['drecco.sudokill.Move']);
goog.addDependency('../../src/move.js', ['drecco.sudokill.Move'], []);
