// This file was autogenerated by /usr/lib/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../src/board.js', ['drecco.sudokill.Board'], ['drecco.sudokill.Move', 'goog.structs.Set']);
goog.addDependency('../../src/move.js', ['drecco.sudokill.Move'], []);
